[[permission]]
identifier = "allow-show-chat-header-menu"
description = "Enables the show_chat_header_menu command without any pre-configured scope."
commands.allow = ["show_chat_header_menu"]

[[permission]]
identifier = "deny-show-chat-header-menu"
description = "Denies the show_chat_header_menu command without any pre-configured scope."
commands.deny = ["show_chat_header_menu"]
